#ifndef BOARD_CONFIG_H
#define BOARD_CONFIG_H

#include "stm32f1xx_hal.h"

#define BOARD_LED_GPIO_PORT GPIOA
#define BOARD_LED_GREEN_PIN GPIO_PIN_5
#define BOARD_LED_YELLOW_PIN GPIO_PIN_6
#define BOARD_LED_RED_PIN GPIO_PIN_7

#define BOARD_ENCODER_RS485_DE_PORT GPIOA
#define BOARD_ENCODER_RS485_DE_PIN GPIO_PIN_8
#define BOARD_ENCODER_CMD_POSITION 0x54
#define BOARD_ENCODER_CAN_SEND_INTERVAL_MS 20U
#define BOARD_ENCODER_REQUEST_TIMEOUT_MS 10U
#define BOARD_ENCODER_DEBUG_LOG_ENABLED 1
#define BOARD_ENCODER_DEBUG_LOG_INTERVAL_MS 100U

#define BOARD_CAN_ID_ENCODER 0x304U
#define BOARD_CAN_CONTROL_ENABLE_RX 1
#define BOARD_CAN_CONTROL_ENABLE_DC_RX 0
#define BOARD_CAN_CONTROL_ENABLE_SERVO_RX 1
#define BOARD_CAN_ID_SERVO 0x1FFU

#define BOARD_SERVO_INA219_ENABLE 1
#define BOARD_SERVO_INA219_I2C_ADDRESS_7BIT 0x40U
#define BOARD_SERVO_INA219_SHUNT_MILLIOHM 5U
#define BOARD_SERVO_INA219_CURRENT_LSB_UA 200U
#define BOARD_SERVO_INA219_LOG_INTERVAL_MS 500U

#endif /* BOARD_CONFIG_H */
