#ifndef BOARD_CONFIG_H
#define BOARD_CONFIG_H

#include "stm32f1xx_hal.h"

#define BOARD_LED_GPIO_PORT GPIOA
#define BOARD_LED_GREEN_PIN GPIO_PIN_5
#define BOARD_LED_YELLOW_PIN GPIO_PIN_6
#define BOARD_LED_RED_PIN GPIO_PIN_7

#define BOARD_ENCODER_RS485_DE_PORT GPIOA
#define BOARD_ENCODER_RS485_DE_PIN GPIO_PIN_8
#define BOARD_ENCODER_CMD_POSITION 0x54
#define BOARD_ENCODER_CAN_SEND_INTERVAL_MS 20U
#define BOARD_ENCODER_REQUEST_TIMEOUT_MS 10U

#define BOARD_CAN_ID_ENCODER 0x304U
#define BOARD_CAN_CONTROL_ENABLE_RX 1
#define BOARD_CAN_ID_DC 0x208U
#define BOARD_CAN_ID_SERVO 0x1FFU
#define BOARD_CAN_RX_DC_SPEED 100

#endif /* BOARD_CONFIG_H */
