[env]
platform = ststm32
board = genericSTM32F446RE
framework = stm32cube

board_build.mcu = stm32f446ret6
board_build.f_cpu = 180000000L

upload_protocol = stlink

board_build.stm32cube.custom_config_header = yes
board_build.stm32cube.custom_system_setup = yes
board_build.stm32cube.disable_embedded_libs = yes

lib_ignore =
    Drivers
    FATFS
    Middlewares
    USB_HOST

build_src_filter =
    +<*>
    +<../lib/FATFS/App/*.c>
    +<../lib/FATFS/Target/*.c>
    +<../lib/Middlewares/Third_Party/FatFs/src/*.c>
    +<../lib/Middlewares/Third_Party/FatFs/src/option/syscall.c>
    +<../lib/Middlewares/Third_Party/FatFs/src/option/cc932.c>
    +<../lib/Middlewares/ST/STM32_USB_Host_Library/Core/Src/*.c>
    +<../lib/Middlewares/ST/STM32_USB_Host_Library/Class/MSC/Src/*.c>
    +<../lib/USB_HOST/App/*.c>
    +<../lib/USB_HOST/Target/*.c>

build_flags =
    -Ilib/FATFS/App
    -Ilib/FATFS/Target
    -Ilib/USB_HOST/App
    -Ilib/USB_HOST/Target
    -Ilib/Middlewares/Third_Party/FatFs/src
    -Ilib/Middlewares/ST/STM32_USB_Host_Library/Core/Inc
    -Ilib/Middlewares/ST/STM32_USB_Host_Library/Class/MSC/Inc

[env:nucleo_f446re]
build_type = release

[env:nucleo_f446re_debug]
build_type = debug
build_flags =
    ${env.build_flags}
    -DDEBUG_LOG_ENABLED=1
